In [1]:
import numpy as np
import genetic as gn

In [2]:
gen1 = gn.Genome()
gen2 = gn.Genome()

print gen1
print gen2

------Genome------
---Chromosome 0: 
convolution:
kernel 0: filter size = (3, 3), stride = 1
kernel 1: filter size = (3, 3), stride = 1
kernel 2: filter size = (3, 3), stride = 1
kernel 3: filter size = (3, 3), stride = 1
---Chromosome 1: 
pooling: size = (2, 2) stride = 1
------Genome------
---Chromosome 0: 
convolution:
kernel 0: filter size = (3, 3), stride = 1
kernel 1: filter size = (3, 3), stride = 1
kernel 2: filter size = (3, 3), stride = 1
kernel 3: filter size = (3, 3), stride = 1
---Chromosome 1: 
pooling: size = (2, 2) stride = 1


In [3]:
print gen1.chromosomes[0].genes[0].kernel

[[ 0.61008405 -1.44239923  0.57215531]
 [ 1.29832363 -1.82968342  0.36199521]
 [-0.73333775  1.03862676 -2.0776337 ]]


In [4]:
gen1.mutate(p = 1)
print gen1.chromosomes[0].genes[0].kernel

[[-0.43206049 -1.62301818 -0.91844164]
 [ 0.53925865 -2.77827009 -0.60823894]
 [-0.70340849  2.10619278 -2.07229981]]


In [5]:

gen1.chromosomes[0].genes[0].kernel = np.random.normal(size = (5,5))
gen1.chromosomes[0].genes[1].kernel = np.random.normal(size = (4,4))
gen1.chromosomes[0].genes[2].kernel = np.random.normal(size = (7,7))
gen1.chromosomes[0].genes[3].kernel = np.random.normal(size = (2,2))
print gen1

------Genome------
---Chromosome 0: 
convolution:
kernel 0: filter size = (5, 5), stride = 1
kernel 1: filter size = (4, 4), stride = 1
kernel 2: filter size = (7, 7), stride = 1
kernel 3: filter size = (2, 2), stride = 1
---Chromosome 1: 
pooling: size = (2, 2) stride = 1


In [6]:
chromosome1 = gen1.chromosomes[0]
chromosome2 = gen2.chromosomes[0]
print chromosome1
print chromosome2


convolution:
kernel 0: filter size = (5, 5), stride = 1
kernel 1: filter size = (4, 4), stride = 1
kernel 2: filter size = (7, 7), stride = 1
kernel 3: filter size = (2, 2), stride = 1

convolution:
kernel 0: filter size = (3, 3), stride = 1
kernel 1: filter size = (3, 3), stride = 1
kernel 2: filter size = (3, 3), stride = 1
kernel 3: filter size = (3, 3), stride = 1



In [7]:
child1, child2 = chromosome1.geneCrossover(chromosome2)
print child1
print child2

convolution:
kernel 0: filter size = (5, 5), stride = 1
kernel 1: filter size = (4, 4), stride = 1
kernel 2: filter size = (7, 7), stride = 1
kernel 3: filter size = (3, 3), stride = 1
kernel 4: filter size = (3, 3), stride = 1

convolution:
kernel 0: filter size = (3, 3), stride = 1
kernel 1: filter size = (3, 3), stride = 1
kernel 2: filter size = (2, 2), stride = 1

